### ISSUE TITLE
Progress Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2220] opened 2023-08-14 12:44 UTC

**Comment by parsakhan21** [comment] 2023-08-25 13:46
Aug 25 - most of guidance is complete - needs review for double checking as well as accessibility; prob wont finish this week

**Comment by parsakhan21** [comment] 2023-08-29 14:00
Aug 29 - complete, need to post on site

**Comment by shey-v** [comment] 2023-09-01 13:30
Have answered the question and added another bit of guidance here - ready for content review @sion-docs

**Comment by sion-docs** [comment] 2023-09-05 16:39
One outstanding question concerning circular/linear progress indicators

**Comment by joshwooding** [comment] 2023-11-27 14:16
Duplicate of #2586

**Closed by joshwooding** 2023-11-27 14:16 UTC
