### ISSUE TITLE
Sharp Country Symbols can be loaded via CSS background (as per rounded symbols)

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#3281] opened 2024-04-23 11:12 UTC
### Area

UI Components

### The problem

Sharp Country symbols can be loaded via CSS background image as per rounded symbols

### The solution

Update CSS of sharp symbols

### Alternatives and examples

n/a

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment] 2024-04-23 19:09
Duplicate of https://github.com/jpmorganchase/salt-ds/issues/3267 ?

**Closed** 2024-05-13 14:14 UTC
Labels: type: enhancement 💡, component: country symbol
