### ISSUE TITLE
Unable to ad fill color to icons

### ISSUE THREAD

**Issue by ankit-link** [jpmorganchase/salt-ds#3285] opened 2024-04-24 07:29 UTC
### Package name(s)

Icons (@salt-ds/icons)

### Package version(s)

   "@salt-ds/core": "^1.25.0",
    "@salt-ds/icons": "^1.11.0",
    "@salt-ds/theme": "^1.14.0",

### Description

fill color is not getting applied to icons. If I give it value like 'red' it works. However, var(--salt-status-negative-foreground) is not working as expected

<ArrowDownIcon
        style={{ fill: "var(--salt-status-negative-foreground)" }}
        size={2}
      />

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment] 2024-04-24 08:07
The code works, please debug your app to see why css variable is not resolving correctly.
https://stackblitz.com/edit/salt-template-xv6dvu?file=App.tsx

**Comment by ankit-link** [comment] 2024-04-24 09:33
I can see it's working in above example. Maybe something wrong at my end. I am using ember app with honeycomb library to render react components. Not sure, If that's messing things up.

**Comment by origami-z** [comment] 2024-04-24 10:44
Raise a question on go/ask-salt, which you can paste screenshot of your CSS inspector. We need to understand what actually happens, e.g., whether the color is overridden by others, or css variable is not resolved because `salt-theme` is not there.

**Comment by ankit-link** [comment] 2024-04-24 10:56
I could see that variable was not resolved in the inspector. I'll share the screenshot in sometime

**Comment by ankit-link** [comment] 2024-04-24 11:02
I have imported import "@salt-ds/theme/index.css" file. Unable to add screenshot here

**Comment by origami-z** [comment] 2024-04-24 11:05
What about `SaltProvider`

**Comment by ankit-link** [comment] 2024-04-24 11:07
Yes added that as well

**Comment by ankit-link** [comment] 2024-04-24 13:13
Even the button component's style is not getting added. I feel css is somehow not getting loaded properly. I can see in inspector variables are not getting resolved

**Comment by origami-z** [comment] 2024-04-26 15:12
Can't reproduce this, closing to indicate not a bug.

**Closed by origami-z** 2024-04-26 15:12 UTC
Labels: type: bug 🪲, status: awaiting triage
