### ISSUE TITLE
Dev theme changes

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2000] opened 2023-07-17 16:53 UTC
Dev version of ticket #1546 

There have been several theme updates which are happening in one of two ways in the codebase:
1. The change is needed due to work being done on the component. Theme can be updated as needed
2. Due to a freeze on the theming, the change will take place in 2024 if currently unnecessary

See 'Update Theme 1546' sheet in teams for all changes listed, and see Github column to see if the change has yet been made
If making the change, please reflect the change accordingly in the appropriate row

cc @pseys  @parsakhan21

**Comment by joshwooding** [comment] 2023-09-29 16:55
Duplicate of #2530

**Closed by joshwooding** 2023-09-29 16:55 UTC
Labels: package: theme, role: dev 💻
