### ISSUE TITLE
Tabstrip Next padding breaks collapse behaviour

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#2781] opened 2023-11-23 16:56 UTC
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

@salt-ds/lab/1.0.0-alpha.22

### Description

Tabstrip has left/right padding added in the following commit:

https://github.com/jpmorganchase/salt-ds/commit/7e14397948a36ae1b6cd7ef382c3d1b678ead51d

This appears to break the collapse behaviour, as the Tabstrip doesn't begin collapsing at the right point.

This implicit padding also makes Tabstrip difficult to use as you can't easily control the spacing to adjacent components

### Steps to reproduce

Place a Tabstip with several tabs in a horizontal <StackLayout> next to some other components. Reduce the width of the browser using window resizing or the devtools panel. You'll notice that the Tabstrip doesn't start collapsing till after it has been forced off the edge of the screen.

### Expected behavior

The tabstrip should never be pushed of the edge of the screen. It should start collapsing at and earlier point.

If you disable the passing css using devtools the behaviour seems correct

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment] 2023-11-24 10:10
Possibly related to #2726

**Comment by Fercas123** [comment] 2024-03-05 11:40
this seems to be resolved by https://github.com/jpmorganchase/salt-ds/pull/2773

**Comment by origami-z** [comment] 2024-03-05 11:46
Still broken on https://www.saltdesignsystem.com/salt/components/tabs/examples#inline?

**Comment by Fercas123** [comment] 2024-03-05 11:52
there seem to be a different issue with inline, to reproduce this one: https://stackblitz.com/edit/salt-test-question-rrs5d9?file=App.tsx,override.css

I'll have a look at the inline one

**Closed** 2024-03-08 13:34 UTC
Labels: type: bug 🪲, status: awaiting triage, component: tabs
