### ISSUE TITLE
Generate static CSS for use by the consumer

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#2549] opened 2023-10-04 13:48 UTC
### Area

Tools

### The problem

Generate the Salt styles as a single static CSS file that can be loaded by the consumer.

This would offer an alternative to the styles injecting themselves dynamically

As part of this, consider whether there are any existing selectors which may clash with the consumer's own selectors (ie. does everything have/need a prefix)

### The solution

- As a consumer, document how to use the CSS
- Update existing docs which may refer to the existing approach
- A single CSS file containing the styles
- Ability to disable the existing style injection (or do we deprecate style injection, once we have this?)

### Alternatives and examples

none

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment] 2023-10-04 22:52
This is a duplicate of https://github.com/jpmorganchase/salt-ds/issues/2532, and one should be closed

**Comment by origami-z** [comment] 2023-11-28 14:01
Can be achieved by #2655, to be tracked by #2532

**Closed by origami-z** 2023-11-28 14:01 UTC
Labels: type: enhancement 💡, status: awaiting triage
