### ISSUE TITLE
Tabs (Labs)

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2884] opened 2024-01-05 09:36 UTC
```[tasklist]
### Tasks
- [ ] #2401
- [x] Update specs for add/close tabs (Design)
- [ ] #4021
```

**Comment by ivan-calderon** [comment] 2024-06-17 20:58
The [Add/remove tabs](https://www.figma.com/design/wh4iwNOuVIpebbV1qgSnxP/Tabs-2?m=auto&node-id=3148-4756&t=J2A0nMMl1BLUls73-1) desing specs and interaction info are ready for review.

**Comment by mark-tate** [comment] 2024-06-24 14:04
Zazu Goal: S(3)
- add/close behaviour to be defined by EOS
- ready for Dev by EOS

**Comment by joshwooding** [comment] 2024-07-01 13:39
Meeting update:

- Focus behaviour has been defined for close button and add button
- Design has been spec'd
- Starting on Dev

**Comment by origami-z** [comment] 2024-08-12 13:37
Aug 12 - closing on overflow, mostly working for add / close, on track for EOS

**Comment by mark-tate** [comment] 2024-09-02 13:48
Espresso goal , merge to Labs in a known state

**Comment by mark-tate** [comment] 2024-09-13 13:49
Sprint Goal: Extended by 1 sprint to add Keyboard Navigation

**Comment by mark-tate** [comment] 2024-09-16 13:38
Frappe Goal: a11y review feedback addressed and pushed to Labs

**Comment by mark-tate** [comment] 2024-09-30 13:36
Galao Goal: Dev complete by EOS, pushed to Labs and wait for feedback from stakeholders

**Comment by origami-z** [comment] 2024-10-03 14:22
FYI - SO questions/92115 asked possibility to keep tab panel mounted between switches (for UITK), it was asked a few times before as well

**Comment by dplsek** [comment] 2024-10-25 13:41
Progress is being made by @joshwooding @ivan-calderon ... addressing some accessibility issues with @jake-costa

**Comment by mark-tate** [comment] 2024-10-28 14:43
Lungo Goal: address a11y feedback and push to Labs, review/publish site docs

**Comment by mark-tate** [comment] 2024-11-11 15:03
Macc Goal: Docs reviewed by Design by EOS
Dev's A11y questions answered by EOS
Publish labs changes

**Comment by origami-z** [comment] 2024-11-14 11:16
From Symphony, UITK `fullWidth` equivalent design / example

**Closed** 2024-11-25 14:51 UTC
Labels: component: tabs, type: component 📦
